runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /welcomePage
  script: main.app
  login: required

#- url: /.*
#  script: main.app
#  login: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
